### ISSUE TITLE
static_binding_error

### ISSUE THREAD

**Issue by omgomgomgomg** [eltuxusb/eltuxusb#28]
Dear Sirs,

running eltuxusb I get
  File "/usr/local/bin/eltuxusb", line 16, in <module>
    from eltuxusb.el_ui import eltuxusb
  File "/usr/local/lib/python2.7/dist-packages/eltuxusb/el_ui.py", line 12, in <module>
    from el_plot import \*  # <- need to clean, dirty
  File "/usr/local/lib/python2.7/dist-packages/eltuxusb/el_plot.py", line 6, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 93, in <module>
    _backend_selection()
  File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 87, in _backend_selection
    if gobject.MainLoop().is_running():
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 62, in **getattr**
    raise AttributeError(_static_binding_error)
AttributeError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183

TIA omg

**Comment by omgomgomgomg** [comment]
/answering to myself

sudo pip install git+http://github.com/eltuxusb/eltuxusb.git#egg=eltuxusb --upgrade

updated eltuxusb matplotlib numpy six python-dateutil pytz mock

Now eltususb dies with
Traceback (most recent call last):
  File "/usr/local/bin/eltuxusb", line 48, in <module>
    app = eltuxusb(debug=args.debug, recover_mode=False).refresh()
  File "/usr/local/lib/python2.7/dist-packages/eltuxusb/el_ui.py", line 124, in refresh
    if self.dev1.init() == False:
  File "/usr/local/lib/python2.7/dist-packages/eltuxusb/el_device.py", line 211, in init
    if self.config_read() == False:
  File "/usr/local/lib/python2.7/dist-packages/eltuxusb/el_device.py", line 326, in config_read
    sent_bytes = self.address.write(0x02, msg, 100)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 631, in write
    intf.bInterfaceNumber,
AttributeError: 'NoneType' object has no attribute 'bInterfaceNumber'

Any clues?

TIA omg
